builds:
  - env:
    - CGO_ENABLED=0
    main: ./cmd/kaf
    goos:
    - linux
    - darwin
    - windows
    goarch:
      - amd64
        arm64
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: infinimesh 
    name: kaf
