// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/cluster.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListClustersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListClustersRequest) Reset()         { *m = ListClustersRequest{} }
func (m *ListClustersRequest) String() string { return proto.CompactTextString(m) }
func (*ListClustersRequest) ProtoMessage()    {}
func (*ListClustersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_963a9d505aa9dcea, []int{0}
}

func (m *ListClustersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClustersRequest.Unmarshal(m, b)
}
func (m *ListClustersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClustersRequest.Marshal(b, m, deterministic)
}
func (m *ListClustersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClustersRequest.Merge(m, src)
}
func (m *ListClustersRequest) XXX_Size() int {
	return xxx_messageInfo_ListClustersRequest.Size(m)
}
func (m *ListClustersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClustersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListClustersRequest proto.InternalMessageInfo

type ListClustersResponse struct {
	Clusters             []*Cluster `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListClustersResponse) Reset()         { *m = ListClustersResponse{} }
func (m *ListClustersResponse) String() string { return proto.CompactTextString(m) }
func (*ListClustersResponse) ProtoMessage()    {}
func (*ListClustersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_963a9d505aa9dcea, []int{1}
}

func (m *ListClustersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClustersResponse.Unmarshal(m, b)
}
func (m *ListClustersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClustersResponse.Marshal(b, m, deterministic)
}
func (m *ListClustersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClustersResponse.Merge(m, src)
}
func (m *ListClustersResponse) XXX_Size() int {
	return xxx_messageInfo_ListClustersResponse.Size(m)
}
func (m *ListClustersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClustersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListClustersResponse proto.InternalMessageInfo

func (m *ListClustersResponse) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

type Cluster struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_963a9d505aa9dcea, []int{2}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ConnectClusterRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectClusterRequest) Reset()         { *m = ConnectClusterRequest{} }
func (m *ConnectClusterRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectClusterRequest) ProtoMessage()    {}
func (*ConnectClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_963a9d505aa9dcea, []int{3}
}

func (m *ConnectClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectClusterRequest.Unmarshal(m, b)
}
func (m *ConnectClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectClusterRequest.Marshal(b, m, deterministic)
}
func (m *ConnectClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectClusterRequest.Merge(m, src)
}
func (m *ConnectClusterRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectClusterRequest.Size(m)
}
func (m *ConnectClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectClusterRequest proto.InternalMessageInfo

func (m *ConnectClusterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ConnectClusterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectClusterResponse) Reset()         { *m = ConnectClusterResponse{} }
func (m *ConnectClusterResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectClusterResponse) ProtoMessage()    {}
func (*ConnectClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_963a9d505aa9dcea, []int{4}
}

func (m *ConnectClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectClusterResponse.Unmarshal(m, b)
}
func (m *ConnectClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectClusterResponse.Marshal(b, m, deterministic)
}
func (m *ConnectClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectClusterResponse.Merge(m, src)
}
func (m *ConnectClusterResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectClusterResponse.Size(m)
}
func (m *ConnectClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectClusterResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListClustersRequest)(nil), "kaf.api.ListClustersRequest")
	proto.RegisterType((*ListClustersResponse)(nil), "kaf.api.ListClustersResponse")
	proto.RegisterType((*Cluster)(nil), "kaf.api.Cluster")
	proto.RegisterType((*ConnectClusterRequest)(nil), "kaf.api.ConnectClusterRequest")
	proto.RegisterType((*ConnectClusterResponse)(nil), "kaf.api.ConnectClusterResponse")
}

func init() { proto.RegisterFile("api/cluster.proto", fileDescriptor_963a9d505aa9dcea) }

var fileDescriptor_963a9d505aa9dcea = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x2c, 0xc8, 0xd4,
	0x4f, 0xce, 0x29, 0x2d, 0x2e, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf,
	0x4e, 0x4c, 0xd3, 0x4b, 0x2c, 0xc8, 0x54, 0x12, 0xe5, 0x12, 0xf6, 0xc9, 0x2c, 0x2e, 0x71, 0x86,
	0xc8, 0x16, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0xb9, 0x70, 0x89, 0xa0, 0x0a, 0x17,
	0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0xe9, 0x70, 0x71, 0x40, 0x0d, 0x2a, 0x96, 0x60, 0x54, 0x60,
	0xd6, 0xe0, 0x36, 0x12, 0xd0, 0x83, 0x1a, 0xa5, 0x07, 0x55, 0x1c, 0x04, 0x57, 0xa1, 0x24, 0xcb,
	0xc5, 0x0e, 0x15, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x02, 0xb3, 0x95, 0xb4, 0xb9, 0x44, 0x9d, 0xf3, 0xf3, 0xf2, 0x52, 0x93, 0x61, 0xf6,
	0x40, 0x6d, 0xc7, 0xaa, 0x58, 0x82, 0x4b, 0x0c, 0x5d, 0x31, 0xc4, 0x4d, 0x46, 0x1b, 0x18, 0xb9,
	0xf8, 0xa0, 0x62, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0xde, 0x5c, 0x3c, 0xc8, 0xce,
	0x17, 0x92, 0x81, 0x3b, 0x12, 0x8b, 0x67, 0xa5, 0x64, 0x71, 0xc8, 0x42, 0xfd, 0x1c, 0xc8, 0xc5,
	0x87, 0x6a, 0xb3, 0x90, 0x1c, 0xc2, 0xcf, 0xd8, 0xdc, 0x2f, 0x25, 0x8f, 0x53, 0x1e, 0x62, 0xa4,
	0x13, 0x6b, 0x14, 0x73, 0x62, 0x41, 0x66, 0x12, 0x1b, 0x38, 0x32, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xdf, 0xa6, 0x2c, 0x59, 0xa1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterServiceClient interface {
	ListClusters(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*ListClustersResponse, error)
	ConnectCluster(ctx context.Context, in *ConnectClusterRequest, opts ...grpc.CallOption) (*ConnectClusterResponse, error)
}

type clusterServiceClient struct {
	cc *grpc.ClientConn
}

func NewClusterServiceClient(cc *grpc.ClientConn) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) ListClusters(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*ListClustersResponse, error) {
	out := new(ListClustersResponse)
	err := c.cc.Invoke(ctx, "/kaf.api.ClusterService/ListClusters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) ConnectCluster(ctx context.Context, in *ConnectClusterRequest, opts ...grpc.CallOption) (*ConnectClusterResponse, error) {
	out := new(ConnectClusterResponse)
	err := c.cc.Invoke(ctx, "/kaf.api.ClusterService/ConnectCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServiceServer is the server API for ClusterService service.
type ClusterServiceServer interface {
	ListClusters(context.Context, *ListClustersRequest) (*ListClustersResponse, error)
	ConnectCluster(context.Context, *ConnectClusterRequest) (*ConnectClusterResponse, error)
}

func RegisterClusterServiceServer(s *grpc.Server, srv ClusterServiceServer) {
	s.RegisterService(&_ClusterService_serviceDesc, srv)
}

func _ClusterService_ListClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).ListClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kaf.api.ClusterService/ListClusters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).ListClusters(ctx, req.(*ListClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_ConnectCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).ConnectCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kaf.api.ClusterService/ConnectCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).ConnectCluster(ctx, req.(*ConnectClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClusterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kaf.api.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListClusters",
			Handler:    _ClusterService_ListClusters_Handler,
		},
		{
			MethodName: "ConnectCluster",
			Handler:    _ClusterService_ConnectCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/cluster.proto",
}
